package net.thejeezed.craftplusplus.creativetabs;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;
import net.thejeezed.craftplusplus.CraftPlusPlus;
import net.thejeezed.craftplusplus.init.ModBlocks;
import net.thejeezed.craftplusplus.init.ModItems;

public class CreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CraftPlusPlus.MOD_ID);
    public static final RegistryObject<CreativeModeTab> CRAFT_TAB = CREATIVE_MODE_TABS.register("craft_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(Blocks.CRAFTING_TABLE))
                    .title(Component.translatable("creativetab.craft_tab"))
                    .displayItems((pParameters, pOutput) -> {
                        pOutput.accept(ModBlocks.WHITE_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.WHITE_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.WHITE_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.ORANGE_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.ORANGE_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.ORANGE_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.MAGENTA_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.MAGENTA_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.MAGENTA_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.LIGHT_BLUE_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.YELLOW_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.YELLOW_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.YELLOW_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.LIME_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.LIME_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.LIME_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.PINK_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.PINK_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.PINK_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.GRAY_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.GRAY_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.GRAY_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.LIGHT_GRAY_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.CYAN_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.CYAN_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.CYAN_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.PURPLE_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.PURPLE_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.PURPLE_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.BLUE_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.BLUE_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.BLUE_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.BROWN_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.BROWN_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.BROWN_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.GREEN_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.GREEN_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.GREEN_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.RED_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.RED_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.RED_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.BLACK_CONCRETE_STAIRS.get());
                        pOutput.accept(ModBlocks.BLACK_CONCRETE_SLAB.get());
                        pOutput.accept(ModBlocks.BLACK_CONCRETE_WALL.get());
                        pOutput.accept(ModBlocks.CHARCOAL_BLOCK.get());
                        pOutput.accept(ModBlocks.COMPRESSED_COPPER.get());
                        pOutput.accept(ModBlocks.SULPHUR_ORE.get());
                        pOutput.accept(ModBlocks.COMPRESSED_SULPHUR.get());
                        pOutput.accept(ModBlocks.SULPHUR_BLOCK.get());
                        pOutput.accept(ModBlocks.SMOOTH_STONE_STAIRS.get());
                        pOutput.accept(ModBlocks.SMOOTH_STONE_WALL.get());
                        pOutput.accept(ModBlocks.STONE_WALL.get());
                        pOutput.accept(ModBlocks.SMOOTH_QUARTZ_WALL.get());
                        pOutput.accept(ModBlocks.QUARTZ_WALL.get());
                        pOutput.accept(ModBlocks.PURPUR_WALL.get());
                        pOutput.accept(ModBlocks.DARK_PRISMARINE_WALL.get());
                        pOutput.accept(ModBlocks.PRISMARINE_BRICK_WALL.get());
                        pOutput.accept(ModBlocks.NETHERRACK_STAIRS.get());
                        pOutput.accept(ModBlocks.NETHERRACK_SLAB.get());
                        pOutput.accept(ModBlocks.NETHERRACK_WALL.get());
                        pOutput.accept(ModBlocks.CRACKED_DEEPSLATE_BRICKS_STAIRS.get());
                        pOutput.accept(ModBlocks.CRACKED_DEEPSLATE_BRICKS_SLAB.get());
                        pOutput.accept(ModBlocks.CRACKED_DEEPSLATE_BRICKS_WALL.get());
                        pOutput.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_STAIRS.get());
                        pOutput.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB.get());
                        pOutput.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_WALL.get());
                        pOutput.accept(ModBlocks.CRACKED_STONE_BRICKS_STAIRS.get());
                        pOutput.accept(ModBlocks.CRACKED_STONE_BRICKS_SLAB.get());
                        pOutput.accept(ModBlocks.CRACKED_STONE_BRICKS_WALL.get());
                        pOutput.accept(ModBlocks.CRACKED_NETHER_BRICKS_STAIRS.get());
                        pOutput.accept(ModBlocks.CRACKED_NETHER_BRICKS_SLAB.get());
                        pOutput.accept(ModBlocks.CRACKED_NETHER_BRICKS_WALL.get());
                        pOutput.accept(ModBlocks.QUARTZ_BRICKS_STAIRS.get());
                        pOutput.accept(ModBlocks.QUARTZ_BRICKS_SLAB.get());
                        pOutput.accept(ModBlocks.QUARTZ_BRICKS_WALL.get());
                        pOutput.accept(ModBlocks.SMOOTH_BASALT_STAIRS.get());
                        pOutput.accept(ModBlocks.SMOOTH_BASALT_SLAB.get());
                        pOutput.accept(ModBlocks.SMOOTH_BASALT_WALL.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_STAIRS.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_SLAB.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_WALL.get());
                        pOutput.accept(ModBlocks.CALCITE_STAIRS.get());
                        pOutput.accept(ModBlocks.CALCITE_SLAB.get());
                        pOutput.accept(ModBlocks.CALCITE_WALL.get());
                        pOutput.accept(ModBlocks.END_STONE_STAIRS.get());
                        pOutput.accept(ModBlocks.END_STONE_SLAB.get());
                        pOutput.accept(ModBlocks.END_STONE_WALL.get());
                        pOutput.accept(ModBlocks.DRIPSTONE_STAIRS.get());
                        pOutput.accept(ModBlocks.DRIPSTONE_SLAB.get());
                        pOutput.accept(ModBlocks.DRIPSTONE_WALL.get());
                        pOutput.accept(ModBlocks.CRACKED_RED_NETHER_BRICKS.get());
                        pOutput.accept(ModBlocks.CRACKED_RED_NETHER_BRICKS_STAIRS.get());
                        pOutput.accept(ModBlocks.CRACKED_RED_NETHER_BRICKS_SLAB.get());
                        pOutput.accept(ModBlocks.CRACKED_RED_NETHER_BRICKS_WALL.get());
                        pOutput.accept(ModBlocks.AMETHYST_STAIRS.get());
                        pOutput.accept(ModBlocks.AMETHYST_SLAB.get());
                        pOutput.accept(ModBlocks.AMETHYST_WALL.get());
                        pOutput.accept(ModBlocks.AMETHYST_BRICK.get());
                        pOutput.accept(ModBlocks.AMETHYST_BRICK_STAIRS.get());
                        pOutput.accept(ModBlocks.AMETHYST_BRICK_SLAB.get());
                        pOutput.accept(ModBlocks.AMETHYST_BRICK_WALL.get());
                        pOutput.accept(ModBlocks.SMOOTH_AMETHYST.get());
                        pOutput.accept(ModBlocks.SMOOTH_AMETHYST_STAIRS.get());
                        pOutput.accept(ModBlocks.SMOOTH_AMETHYST_SLAB.get());
                        pOutput.accept(ModBlocks.SMOOTH_AMETHYST_WALL.get());
                        pOutput.accept(ModBlocks.CHISELED_AMETHYST.get());
                        pOutput.accept(ModBlocks.KILN.get());
                        pOutput.accept(ModItems.COPPER_BUCKET.get());
                        pOutput.accept(ModItems.COPPER_WATER_BUCKET.get());
                        pOutput.accept(ModItems.COPPER_MILK_BUCKET.get());
                        pOutput.accept(ModItems.COPPER_SHOVEL.get());
                        pOutput.accept(ModItems.COPPER_PICKAXE.get());
                        pOutput.accept(ModItems.COPPER_AXE.get());
                        pOutput.accept(ModItems.COPPER_HOE.get());
                        pOutput.accept(ModItems.COPPER_SWORD.get());
                        pOutput.accept(ModItems.COPPER_HELMET.get());
                        pOutput.accept(ModItems.COPPER_CHESTPLATE.get());
                        pOutput.accept(ModItems.COPPER_LEGGINGS.get());
                        pOutput.accept(ModItems.COPPER_BOOTS.get());
                        pOutput.accept(ModItems.COPPER_HORSE_ARMOR.get());
                        pOutput.accept(ModItems.NETHERITE_HORSE_ARMOR.get());
                        pOutput.accept(ModItems.SEA_SOUP.get());
                        pOutput.accept(ModItems.RAW_TENTACLE.get());
                        pOutput.accept(ModItems.COOKED_TENTACLE.get());
                        //pOutput.accept(ModItems.STRAFER_SPAWN_EGG.get());
                        pOutput.accept(ModItems.SULPHUR_ZOMBIE_SPAWN_EGG.get());
                        pOutput.accept(ModItems.MAGIC_MIRROR.get());
                        pOutput.accept(ModItems.TURTLE_SHELL_CHESTPLATE.get());
                        pOutput.accept(ModItems.TURTLE_SHELL_LEGGINGS.get());
                        pOutput.accept(ModItems.TURTLE_SHELL_BOOTS.get());
                        pOutput.accept(ModItems.SUGARCANE_ON_A_STICK.get());
                        pOutput.accept(ModItems.COTTON_SEEDS.get());
                        pOutput.accept(ModItems.SULPHUR_CHUNK.get());
                        pOutput.accept(ModItems.COTTON.get());
                        pOutput.accept(ModItems.DYNAMITE.get());
                        pOutput.accept(ModItems.ECHO_BLASTER.get());
                        pOutput.accept(ModItems.COPPER_NUGGET.get());
                        pOutput.accept(ModItems.CALM_NIGHT_MUSIC_DISC.get());
                        pOutput.accept(ModItems.COUNTRY_ROAD_MUSIC_DISC.get());
                    })
                    .build());


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
